// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: consensus.proto

package consensus

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Block represents a single entry in the append-only chain
type Block struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         int32                  `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	PrevHash      string                 `protobuf:"bytes,2,opt,name=prev_hash,json=prevHash,proto3" json:"prev_hash,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	OrderId       int32                  `protobuf:"varint,4,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Stock         string                 `protobuf:"bytes,5,opt,name=stock,proto3" json:"stock,omitempty"`
	OrderType     string                 `protobuf:"bytes,6,opt,name=order_type,json=orderType,proto3" json:"order_type,omitempty"`
	Quantity      string                 `protobuf:"bytes,7,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Price         string                 `protobuf:"bytes,8,opt,name=price,proto3" json:"price,omitempty"`
	NodeName      string                 `protobuf:"bytes,9,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	Signature     string                 `protobuf:"bytes,10,opt,name=signature,proto3" json:"signature,omitempty"`
	PublicKey     string                 `protobuf:"bytes,11,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	Hash          string                 `protobuf:"bytes,12,opt,name=hash,proto3" json:"hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Block) Reset() {
	*x = Block{}
	mi := &file_consensus_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Block) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Block) ProtoMessage() {}

func (x *Block) ProtoReflect() protoreflect.Message {
	mi := &file_consensus_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Block.ProtoReflect.Descriptor instead.
func (*Block) Descriptor() ([]byte, []int) {
	return file_consensus_proto_rawDescGZIP(), []int{0}
}

func (x *Block) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *Block) GetPrevHash() string {
	if x != nil {
		return x.PrevHash
	}
	return ""
}

func (x *Block) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Block) GetOrderId() int32 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *Block) GetStock() string {
	if x != nil {
		return x.Stock
	}
	return ""
}

func (x *Block) GetOrderType() string {
	if x != nil {
		return x.OrderType
	}
	return ""
}

func (x *Block) GetQuantity() string {
	if x != nil {
		return x.Quantity
	}
	return ""
}

func (x *Block) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *Block) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *Block) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *Block) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *Block) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

// ProposeRequest is what the Leader sends to each Validator
type ProposeRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Block           *Block                 `protobuf:"bytes,1,opt,name=block,proto3" json:"block,omitempty"`
	OraclePrice     string                 `protobuf:"bytes,2,opt,name=oracle_price,json=oraclePrice,proto3" json:"oracle_price,omitempty"`
	OracleTimestamp string                 `protobuf:"bytes,3,opt,name=oracle_timestamp,json=oracleTimestamp,proto3" json:"oracle_timestamp,omitempty"`
	Signature       string                 `protobuf:"bytes,4,opt,name=signature,proto3" json:"signature,omitempty"`                              // user's ECDSA signature
	PublicKey       string                 `protobuf:"bytes,5,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`             // user's PEM public key
	SignedMessage   string                 `protobuf:"bytes,6,opt,name=signed_message,json=signedMessage,proto3" json:"signed_message,omitempty"` // the exact message that was signed
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ProposeRequest) Reset() {
	*x = ProposeRequest{}
	mi := &file_consensus_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProposeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProposeRequest) ProtoMessage() {}

func (x *ProposeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_consensus_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProposeRequest.ProtoReflect.Descriptor instead.
func (*ProposeRequest) Descriptor() ([]byte, []int) {
	return file_consensus_proto_rawDescGZIP(), []int{1}
}

func (x *ProposeRequest) GetBlock() *Block {
	if x != nil {
		return x.Block
	}
	return nil
}

func (x *ProposeRequest) GetOraclePrice() string {
	if x != nil {
		return x.OraclePrice
	}
	return ""
}

func (x *ProposeRequest) GetOracleTimestamp() string {
	if x != nil {
		return x.OracleTimestamp
	}
	return ""
}

func (x *ProposeRequest) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *ProposeRequest) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *ProposeRequest) GetSignedMessage() string {
	if x != nil {
		return x.SignedMessage
	}
	return ""
}

// VoteResponse is what the Validator sends back
type VoteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Approve       bool                   `protobuf:"varint,2,opt,name=approve,proto3" json:"approve,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VoteResponse) Reset() {
	*x = VoteResponse{}
	mi := &file_consensus_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VoteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoteResponse) ProtoMessage() {}

func (x *VoteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_consensus_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoteResponse.ProtoReflect.Descriptor instead.
func (*VoteResponse) Descriptor() ([]byte, []int) {
	return file_consensus_proto_rawDescGZIP(), []int{2}
}

func (x *VoteResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *VoteResponse) GetApprove() bool {
	if x != nil {
		return x.Approve
	}
	return false
}

func (x *VoteResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// CommitRequest is sent by the Leader after consensus is reached
type CommitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Block         *Block                 `protobuf:"bytes,1,opt,name=block,proto3" json:"block,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitRequest) Reset() {
	*x = CommitRequest{}
	mi := &file_consensus_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitRequest) ProtoMessage() {}

func (x *CommitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_consensus_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitRequest.ProtoReflect.Descriptor instead.
func (*CommitRequest) Descriptor() ([]byte, []int) {
	return file_consensus_proto_rawDescGZIP(), []int{3}
}

func (x *CommitRequest) GetBlock() *Block {
	if x != nil {
		return x.Block
	}
	return nil
}

// CommitResponse acknowledges that the Validator appended the block
type CommitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Index         int32                  `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	ChainLength   int32                  `protobuf:"varint,3,opt,name=chain_length,json=chainLength,proto3" json:"chain_length,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitResponse) Reset() {
	*x = CommitResponse{}
	mi := &file_consensus_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitResponse) ProtoMessage() {}

func (x *CommitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_consensus_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitResponse.ProtoReflect.Descriptor instead.
func (*CommitResponse) Descriptor() ([]byte, []int) {
	return file_consensus_proto_rawDescGZIP(), []int{4}
}

func (x *CommitResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CommitResponse) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *CommitResponse) GetChainLength() int32 {
	if x != nil {
		return x.ChainLength
	}
	return 0
}

var File_consensus_proto protoreflect.FileDescriptor

const file_consensus_proto_rawDesc = "" +
	"\n" +
	"\x0fconsensus.proto\x12\tconsensus\"\xc8\x02\n" +
	"\x05Block\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x05R\x05index\x12\x1b\n" +
	"\tprev_hash\x18\x02 \x01(\tR\bprevHash\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\x12\x19\n" +
	"\border_id\x18\x04 \x01(\x05R\aorderId\x12\x14\n" +
	"\x05stock\x18\x05 \x01(\tR\x05stock\x12\x1d\n" +
	"\n" +
	"order_type\x18\x06 \x01(\tR\torderType\x12\x1a\n" +
	"\bquantity\x18\a \x01(\tR\bquantity\x12\x14\n" +
	"\x05price\x18\b \x01(\tR\x05price\x12\x1b\n" +
	"\tnode_name\x18\t \x01(\tR\bnodeName\x12\x1c\n" +
	"\tsignature\x18\n" +
	" \x01(\tR\tsignature\x12\x1d\n" +
	"\n" +
	"public_key\x18\v \x01(\tR\tpublicKey\x12\x12\n" +
	"\x04hash\x18\f \x01(\tR\x04hash\"\xea\x01\n" +
	"\x0eProposeRequest\x12&\n" +
	"\x05block\x18\x01 \x01(\v2\x10.consensus.BlockR\x05block\x12!\n" +
	"\foracle_price\x18\x02 \x01(\tR\voraclePrice\x12)\n" +
	"\x10oracle_timestamp\x18\x03 \x01(\tR\x0foracleTimestamp\x12\x1c\n" +
	"\tsignature\x18\x04 \x01(\tR\tsignature\x12\x1d\n" +
	"\n" +
	"public_key\x18\x05 \x01(\tR\tpublicKey\x12%\n" +
	"\x0esigned_message\x18\x06 \x01(\tR\rsignedMessage\"Y\n" +
	"\fVoteResponse\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x18\n" +
	"\aapprove\x18\x02 \x01(\bR\aapprove\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"7\n" +
	"\rCommitRequest\x12&\n" +
	"\x05block\x18\x01 \x01(\v2\x10.consensus.BlockR\x05block\"a\n" +
	"\x0eCommitResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x14\n" +
	"\x05index\x18\x02 \x01(\x05R\x05index\x12!\n" +
	"\fchain_length\x18\x03 \x01(\x05R\vchainLength2\x90\x01\n" +
	"\x10ConsensusService\x12=\n" +
	"\aPropose\x12\x19.consensus.ProposeRequest\x1a\x17.consensus.VoteResponse\x12=\n" +
	"\x06Commit\x12\x18.consensus.CommitRequest\x1a\x19.consensus.CommitResponseB$Z\"github.com/trading/nodes/consensusb\x06proto3"

var (
	file_consensus_proto_rawDescOnce sync.Once
	file_consensus_proto_rawDescData []byte
)

func file_consensus_proto_rawDescGZIP() []byte {
	file_consensus_proto_rawDescOnce.Do(func() {
		file_consensus_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_consensus_proto_rawDesc), len(file_consensus_proto_rawDesc)))
	})
	return file_consensus_proto_rawDescData
}

var file_consensus_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_consensus_proto_goTypes = []any{
	(*Block)(nil),          // 0: consensus.Block
	(*ProposeRequest)(nil), // 1: consensus.ProposeRequest
	(*VoteResponse)(nil),   // 2: consensus.VoteResponse
	(*CommitRequest)(nil),  // 3: consensus.CommitRequest
	(*CommitResponse)(nil), // 4: consensus.CommitResponse
}
var file_consensus_proto_depIdxs = []int32{
	0, // 0: consensus.ProposeRequest.block:type_name -> consensus.Block
	0, // 1: consensus.CommitRequest.block:type_name -> consensus.Block
	1, // 2: consensus.ConsensusService.Propose:input_type -> consensus.ProposeRequest
	3, // 3: consensus.ConsensusService.Commit:input_type -> consensus.CommitRequest
	2, // 4: consensus.ConsensusService.Propose:output_type -> consensus.VoteResponse
	4, // 5: consensus.ConsensusService.Commit:output_type -> consensus.CommitResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_consensus_proto_init() }
func file_consensus_proto_init() {
	if File_consensus_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_consensus_proto_rawDesc), len(file_consensus_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_consensus_proto_goTypes,
		DependencyIndexes: file_consensus_proto_depIdxs,
		MessageInfos:      file_consensus_proto_msgTypes,
	}.Build()
	File_consensus_proto = out.File
	file_consensus_proto_goTypes = nil
	file_consensus_proto_depIdxs = nil
}
