# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: oracle.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'oracle.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0coracle.proto\x12\x06oracle\"\x1e\n\x0cPriceRequest\x12\x0e\n\x06ticker\x18\x01 \x01(\t\"`\n\rPriceResponse\x12\x0e\n\x06ticker\x18\x01 \x01(\t\x12\x17\n\x0f\x65xecution_price\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\t\x12\x13\n\x0bmarket_time\x18\x04 \x01(\t2H\n\rOracleService\x12\x37\n\x08GetPrice\x12\x14.oracle.PriceRequest\x1a\x15.oracle.PriceResponseB$Z\x1fgithub.com/trading/nodes/oracle\x90\x01\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'oracle_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\037github.com/trading/nodes/oracle\220\001\001'
  _globals['_PRICEREQUEST']._serialized_start=24
  _globals['_PRICEREQUEST']._serialized_end=54
  _globals['_PRICERESPONSE']._serialized_start=56
  _globals['_PRICERESPONSE']._serialized_end=152
  _globals['_ORACLESERVICE']._serialized_start=154
  _globals['_ORACLESERVICE']._serialized_end=226
_builder.BuildServices(DESCRIPTOR, 'oracle_pb2', _globals)
# @@protoc_insertion_point(module_scope)
