// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: oracle.proto

package oracle

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PriceRequest is sent by a node asking for the current price of a stock
type PriceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ticker        string                 `protobuf:"bytes,1,opt,name=ticker,proto3" json:"ticker,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PriceRequest) Reset() {
	*x = PriceRequest{}
	mi := &file_oracle_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PriceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PriceRequest) ProtoMessage() {}

func (x *PriceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_oracle_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PriceRequest.ProtoReflect.Descriptor instead.
func (*PriceRequest) Descriptor() ([]byte, []int) {
	return file_oracle_proto_rawDescGZIP(), []int{0}
}

func (x *PriceRequest) GetTicker() string {
	if x != nil {
		return x.Ticker
	}
	return ""
}

// PriceResponse is returned by the oracle with the live execution price
type PriceResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Ticker         string                 `protobuf:"bytes,1,opt,name=ticker,proto3" json:"ticker,omitempty"`
	ExecutionPrice string                 `protobuf:"bytes,2,opt,name=execution_price,json=executionPrice,proto3" json:"execution_price,omitempty"`
	Timestamp      string                 `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                     // when the Oracle produced this quote (freshness checks)
	MarketTime     string                 `protobuf:"bytes,4,opt,name=market_time,json=marketTime,proto3" json:"market_time,omitempty"` // time of the market data the price comes from
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PriceResponse) Reset() {
	*x = PriceResponse{}
	mi := &file_oracle_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PriceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PriceResponse) ProtoMessage() {}

func (x *PriceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_oracle_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PriceResponse.ProtoReflect.Descriptor instead.
func (*PriceResponse) Descriptor() ([]byte, []int) {
	return file_oracle_proto_rawDescGZIP(), []int{1}
}

func (x *PriceResponse) GetTicker() string {
	if x != nil {
		return x.Ticker
	}
	return ""
}

func (x *PriceResponse) GetExecutionPrice() string {
	if x != nil {
		return x.ExecutionPrice
	}
	return ""
}

func (x *PriceResponse) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *PriceResponse) GetMarketTime() string {
	if x != nil {
		return x.MarketTime
	}
	return ""
}

var File_oracle_proto protoreflect.FileDescriptor

const file_oracle_proto_rawDesc = "" +
	"\n" +
	"\foracle.proto\x12\x06oracle\"&\n" +
	"\fPriceRequest\x12\x16\n" +
	"\x06ticker\x18\x01 \x01(\tR\x06ticker\"\x8f\x01\n" +
	"\rPriceResponse\x12\x16\n" +
	"\x06ticker\x18\x01 \x01(\tR\x06ticker\x12'\n" +
	"\x0fexecution_price\x18\x02 \x01(\tR\x0eexecutionPrice\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\tR\ttimestamp\x12\x1f\n" +
	"\vmarket_time\x18\x04 \x01(\tR\n" +
	"marketTime2H\n" +
	"\rOracleService\x127\n" +
	"\bGetPrice\x12\x14.oracle.PriceRequest\x1a\x15.oracle.PriceResponseB$Z\x1fgithub.com/trading/nodes/oracle\x90\x01\x01b\x06proto3"

var (
	file_oracle_proto_rawDescOnce sync.Once
	file_oracle_proto_rawDescData []byte
)

func file_oracle_proto_rawDescGZIP() []byte {
	file_oracle_proto_rawDescOnce.Do(func() {
		file_oracle_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_oracle_proto_rawDesc), len(file_oracle_proto_rawDesc)))
	})
	return file_oracle_proto_rawDescData
}

var file_oracle_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_oracle_proto_goTypes = []any{
	(*PriceRequest)(nil),  // 0: oracle.PriceRequest
	(*PriceResponse)(nil), // 1: oracle.PriceResponse
}
var file_oracle_proto_depIdxs = []int32{
	0, // 0: oracle.OracleService.GetPrice:input_type -> oracle.PriceRequest
	1, // 1: oracle.OracleService.GetPrice:output_type -> oracle.PriceResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_oracle_proto_init() }
func file_oracle_proto_init() {
	if File_oracle_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_oracle_proto_rawDesc), len(file_oracle_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_oracle_proto_goTypes,
		DependencyIndexes: file_oracle_proto_depIdxs,
		MessageInfos:      file_oracle_proto_msgTypes,
	}.Build()
	File_oracle_proto = out.File
	file_oracle_proto_goTypes = nil
	file_oracle_proto_depIdxs = nil
}
