# Generated by Django 6.0.3 on 2026-04-05 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='execution_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='nonce',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
