# Generated by Django 6.0.3 on 2026-04-05 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0002_order_execution_price_order_nonce'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='limit_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True),
        ),
    ]
