# Generated by Django 6.0.6 on 2026-06-28 19:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0006_add_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='leverage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='trade_type',
            field=models.CharField(choices=[('STOCK', 'Stock'), ('CFD', 'CFD')], default='STOCK', max_length=5),
        ),
        migrations.CreateModel(
            name='CFDPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('LONG', 'Long'), ('SHORT', 'Short')], max_length=5)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=15)),
                ('entry_price', models.DecimalField(decimal_places=4, max_digits=15)),
                ('leverage', models.IntegerField()),
                ('margin_used', models.DecimalField(decimal_places=4, max_digits=15)),
                ('is_open', models.BooleanField(default=True)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('close_price', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('pnl', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trading.stock')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cfd_positions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'is_open'], name='cfd_user_open_idx')],
            },
        ),
    ]
