# Generated by Django 6.0.6 on 2026-06-28 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0007_cfd_positions'),
    ]

    operations = [
        migrations.AddField(
            model_name='cfdposition',
            name='stop_loss',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='cfdposition',
            name='take_profit',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='sltp_triggered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='stop_loss',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='take_profit',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True),
        ),
    ]
