# Generated by Django 6.0.6 on 2026-09-19 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0013_order_close_types'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='orderapproval',
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name='orderapproval',
            name='approval_order_idx',
        ),
        migrations.DeleteModel(
            name='OrderApproval',
        ),
    ]
