# Generated by Django 6.0.5 on 2026-09-23 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0016_node_keys_and_block_hash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='sltp_triggered',
        ),
        migrations.AddField(
            model_name='order',
            name='stop_loss_qty',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='take_profit_qty',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True),
        ),
    ]
