# Generated by Django 6.0.5 on 2026-09-23 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0017_order_sltp_quantities'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='reject_reason',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
